var cards=[{"cost":"2F",
    "card_name":"Fire Warrior",
    "foto":"fire_warrior.jpg",
    "types":["soldier"],
    "subtypes":["human","mage"],
    "effects":["When self comes into the battlefield, it deals 1 damage to its controller","Loses 1 regen each turn"],
    "description":"First card !\n What do you have to say ?",
    "attack":2,
    "speed":1,
    "regeneration":0,
    "defense":2}];